# Generated by Django 5.1.3 on 2025-02-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='frontpage_pdfs/'),
        ),
    ]
