runtime: python311
entrypoint: gunicorn -b :$PORT personalWebpage.wsgi:application

env_variables:
  DJANGO_SETTINGS_MODULE: "personalWebpage.settings"

instance_class: F2

handlers:
  - url: /static
    static_dir: static/
  - url: /media
    static_dir: media/

automatic_scaling:
  min_instances: 1
  max_instances: 1
