services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: personalWebpage_db
      POSTGRES_USER: Krusovice
      POSTGRES_PASSWORD: fedefrede
      POSTGRES_MULTIPLE_DATABASES: personalWebpage_db,airflow
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    #entrypoint: ["bash", "-c", "docker-entrypoint.sh postgres & sleep 10 && psql -U $POSTGRES_USER -c 'CREATE DATABASE airflow;'"]

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "Krusovice", "-d", "personalWebpage_db"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    command: >
          bash -c "python manage.py migrate &&
                   python manage.py collectstatic --noinput &&
                   gunicorn --bind 0.0.0.0:8000 personalWebpage.wsgi:application"

    volumes:
      - ./django:/personalWebpage/django

    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

    environment:
      - DATABASE_URL=postgres://Krusovice:fedefrede@postgres:5432/personalWebpage_db

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    volumes:
      - ./nginx_dev.conf:/etc/nginx/nginx.conf # Comment for production
      #- ./nginx.conf:/etc/nginx/nginx.conf # Uncomment for production
      - ./conf.d:/etc/nginx/conf.d
      - ./django/staticfiles:/personalWebpage/django/staticfiles
      - ./django/media:/personalWebpage/django/media
      #- /etc/letsencrypt/:/etc/letsencrypt # Uncomment for production
    ports:
      - "80:80"
      - "443:443"  # Expose port 443 for HTTPS
    depends_on:
      - django


  airflow-webserver:
    image: apache/airflow:2.10.5
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres_db/airflow
      - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
      - AIRFLOW_CONN_POSTGRES_DEFAULT=postgresql+psycopg2://airflow:airflow@postgres_db/postgres
    command: [ "bash", "-c", "pip install -r /requirements.txt && exec airflow webserver" ]

    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/requirements.txt:/requirements.txt
    depends_on:
      - airflow-init
    restart: always

  airflow-scheduler:
    image: apache/airflow:2.10.5
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres_db/airflow
      - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
      - AIRFLOW_CONN_POSTGRES_DEFAULT=postgresql+psycopg2://airflow:airflow@postgres_db/postgres
    command: [ "bash", "-c", "pip install -r /requirements.txt && exec airflow scheduler" ]

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/requirements.txt:/requirements.txt
    depends_on:
      - airflow-init
    restart: always

  airflow-cli:
    image: apache/airflow:2.10.5
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres_db/airflow
      - AIRFLOW_CONN_POSTGRES_DEFAULT=postgresql+psycopg2://airflow:airflow@postgres_db/postgres
    command: ["bash"]
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/requirements.txt:/requirements.txt
    depends_on:
      - airflow-init

  airflow-init:
    image: apache/airflow:2.10.5
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db upgrade
        exec airflow users create \
          --username airflow \
          --password airflow \
          --firstname Airflow \
          --lastname Admin \
          --role Admin \
          --email admin@example.com
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres_db/airflow
    restart: on-failure