# Generated by Django 5.1.3 on 2025-02-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='closing_price',
            field=models.DecimalField(db_column='close', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='date',
            field=models.DateField(db_column='date'),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='ticker',
            field=models.CharField(db_column='ticker', max_length=10),
        ),
    ]
