# Generated by Django 5.1.3 on 2025-02-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0002_alter_stockprice_closing_price_alter_stockprice_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockprice',
            table='stock_prices',
        ),
    ]
